<?php

namespace AppBundle\Repository;

/**
 * DemandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemandeRepository extends \Doctrine\ORM\EntityRepository
{

    public function findNbDemandesByYear($annee){

        $qb = $this->createQueryBuilder('d');
        $qb->select('COUNT(d)')
            ->where('d.annee = :annee')
            ->setParameter('annee', $annee);

        $query = $qb->getQuery();

        return $query->getSingleScalarResult();

    }

    public function findNbDemandeByEtat($etat){

        $qb = $this->createQueryBuilder('d');
        $qb->select('COUNT(d)')
            ->where('d.etatDemande = :etat')
            ->setParameter('etat', $etat);

        $query = $qb->getQuery();

        return $query->getSingleScalarResult();

    }

    public function findDemandesByType($type){

        $qb = $this->createQueryBuilder('d');
        $qb->select('COUNT(d)')
            ->where('d.typeDemande = :type')
            ->setParameter('type', $type);

        $query = $qb->getQuery();

        return $query->getSingleScalarResult();

    }

    public function findDemandesByEtat($etat){

        $qb = $this->createQueryBuilder('d');
        $qb->select('d')
            ->where('d.etatDemande = :etat')
            ->setParameter('etat', $etat);

        $query = $qb->getQuery();

        return $query->getResult();

    }

    public function findDemandesByMatriculeEtat($matricule, $etat){

        $qb = $this->createQueryBuilder('d');
        $qb->select('d')
            ->join('d.etudiant', 'e')
            ->where('e.mention = :matricule');

        if($etat != null){
            $qb->andWhere('d.etatDemande = :etat');
            $qb->setParameter('etat', $etat);
        }

        $qb->setParameter('matricule', $matricule);


        $query = $qb->getQuery();

        return $query->getResult();

    }

    public function findEtudiantDemandes($etudiant_id){

        $qb = $this->createQueryBuilder('d');
        $qb->select('d')
            ->join('d.etudiant', 'e')
            ->where('e.id = :etudiant')
            ->setParameter('etudiant', $etudiant_id);

        $query = $qb->getQuery();

        return $query->getResult();

    }

}
