<?php

namespace AppBundle\Repository;

/**
 * DiplomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiplomeRepository extends \Doctrine\ORM\EntityRepository
{
    public function countDiplomes(){

        $qb = $this->createQueryBuilder('d');
        $qb->select('SUM(d.quantite)');

        $query = $qb->getQuery();

        return $query->getSingleScalarResult();

    }
}
